config/routes.rb
Rails.application.routes.draw do
  root to: "home#index"
  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations'
  }
  
  resources :listings
  resources :baby_sitter_registrations do
  resources :booking_details 
  end
  resources :dashboard

  get '/baby_sitters/:id', to: 'baby_sitter_registrations#show', as: :baby_sitter
  get '/listings', to: 'listings#index'
  resources :home

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/baby_sitter_registration.rb
class BabySitterRegistration < ApplicationRecord
has_one_attached :upload_image

belongs_to :user
has_many :booking_detail

validates :amount, numericality: true
  
end

app/controllers/baby_sitter_registrations_controller.rb
class BabySitterRegistrationsController < ApplicationController
    before_action :authenticate_user!,except:[:index]
    before_action :find_babysitter,only: [:edit, :update, :destroy]
    before_action :authorise_user!, only: [:edit, :update, :destroy]

    # listing all baby sitters
    def index
    @babysitters = BabySitterRegistration.all
    end
    # create new baby sitter
    def new
        @baby_sitter = BabySitterRegistration.new
    end

    def create
        @baby_sitter = BabySitterRegistration.new(baby_sitter_registration_params)
        @baby_sitter.user_id=current_user.id
       
        if(@baby_sitter.save)
            redirect_to dashboard_index_path
        else
            render 'new'
        end
    end
    
    #display the details of a baby sitter
    def show
        @baby_sitter= BabySitterRegistration.find(params[:id])
    end

    #update the details of a baby sitter
    def update
        if (@babysitter.update(baby_sitter_registration_params))
            redirect_to  dashboard_index_path, notice: "UPDATED!"
        else
            render 'edit'
        end
    end

    # def destroy
    #     @babysitter.delete

    #     redirect_to  "/"
    # end

    private

    def baby_sitter_registration_params
        params.require(:baby_sitter_registration).permit(:first_name,:last_name, :gender, :country,:city, :language, :description, :available_date,:amount, :upload_image)
    end

    def find_babysitter
        @babysitter = BabySitterRegistration.find(params[:id])
    end

    def authorise_user!
        return true if current_user.id == @babysitter.user_id
    end
end

app/helpers/baby_sitter_registrations_helper.rb
module BabySitterRegistrationsHelper
end

app/views/baby_sitter_registrations/_registration_form.html.erb
<%= form_with(model: baby_sitter_registration, local: true,class:"form") do |form| %>

<section>

  <% if baby_sitter_registration.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(baby_sitter_registration.errors.count, "error") %> prohibited this event from being saved:</h2>

      <ul>
        <% baby_sitter_registration.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
<div class ="container">
<h2>Complete your profile </h2><br>
  <div class="field">
    <%= form.label :First_name, class:"col-5"%>
     <%= form.text_field :first_name,:required => true,class:"col-6" %>
  </div>

  <div class="field">
    <%= form.label :Last_name,class:"col-5" %>
     <%= form.text_field :last_name,class:"col-6",:required => true %>
  </div>

  <div class="field">
   
    <%= form.label :Gender,class:"col-5" %>
    <%= form.label :Male %>
    <%= form.radio_button :gender, 'Male' %>&nbsp
     <%= form.label :Female %>
    <%= form.radio_button :gender, 'Female' %>
  </div>

  <div class="field">
    <%= form.label :Country ,class: "col-5" %>
    <%= form.text_field :country,:required => true, class:"col-6" %>
  </div>

  <div class="field">
    <%= form.label :City, class: "col-5"%>
    <%= form.text_field :city, :required => true ,class:"col-6"%>
  </div>

  <div class="field">
    <%= form.label :Preferred_Languages, class: "col-5" %>
    <%= form.text_area :language, :required => true,class:"col-6" %>
  </div>
  
  <div class="field">
    <%= form.label :Description , :plcaeholder => "(eg:about yourself,experience etc.)",class: "col-5" %>
    <%= form.text_area :description,:required => true,class: "col-6" %>
  </div>
 <div class="field">
    <%= form.label :available_date, class:"col-5" %>
    <%= form.date_select :available_date, :required => true, class:"col-6" %>
  </div>
  <div class="field">
    <%= form.label :Amount_per_hour, class: "col-5" %>
    <%= form.text_field :amount,:required => true,class:"col-6" %>
  </div>

 <div class="field">
    <%= form.label :Upload_Photo , accept: 'image/png, image/gif, image/jpeg, image/jpg',class:"col-5"%>
    <%= form.file_field :upload_image , :required => true,class:"col-4" %>
  </div>
<br>
  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>
</div>
</section>

app/views/baby_sitter_registrations/edit.html.erb
 
<%= render 'registration_form' ,baby_sitter_registration: @babysitter %>

app/views/baby_sitter_registrations/index.html.erb
<h2 class="lists">Meet And Book Our BabySitters</h2>
<div class ="search">
<%= form_tag listings_path, :method=>'get' do %>
 <%= text_field_tag :city,"",placeholder: " Search by City ",class:"col-8" ,:required=>"true"%>
 <%= submit_tag "Search" ,class:"next" %><br>
<%end %>
</div>
<div class = "grid-container">
 <%# <%= params[:city]  %> 
<% @babysitters.each do |babysitter| %>
<div class ="grid-item">
<p class= "preview"><%= image_tag (babysitter.upload_image) if babysitter.upload_image.attached? %></p>
<h2> <%= babysitter.first_name + ' ' + babysitter.last_name %></h2>
<div><strong>Location: <%= babysitter.city%></strong></div>
<div><strong> Amount/hr: $<%= babysitter.amount%></strong></div><br>
<div><%= button_to "View more" , baby_sitter_path(babysitter) , method: :get ,class:'view'%></div>
</div>

<% end %>

</div>

app/views/baby_sitter_registrations/new.html.erb
<%# <p id="notice"><%= notice %></p> 
<%= render 'registration_form' ,baby_sitter_registration: @baby_sitter %>

app/views/baby_sitter_registrations/show.html.erb
   
<div class="container box" ><br>
<h1><%= @baby_sitter.first_name + ' ' + @baby_sitter.last_name %></h1> <br>
<p class = "preview"><%= image_tag (@baby_sitter.upload_image) if @baby_sitter.upload_image.attached? %></p>
<div>
<p><strong>Country:</strong> <%= @baby_sitter.country%></p>
<p><strong>Prefered City:</strong> <%= @baby_sitter.city %></p>
<p><strong>Languages:</strong> <%= @baby_sitter.language %></p>
<p><strong>Available_Date:</strong> <%= @baby_sitter.available_date %></p>
<p><strong>About myself:</strong> <%= @baby_sitter.description %></p>
<p><strong>Amount/hr:</strong> <%= @baby_sitter.amount %></p><br>
</div>
<% if user_signed_in? && !current_user.is_baby_sitter %>
<%= button_to "BOOK_NOW" , new_baby_sitter_registration_booking_detail_path({baby_sitter_registration_id: @baby_sitter.id}),method: :get,class:"continue" %>
<%end %>
</div>

  