config/routes.rb
Rails.application.routes.draw do
  root to: "home#index"
  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations'
  }
  
  resources :listings
  resources :baby_sitter_registrations do
  resources :booking_details 
  end
  resources :dashboard

  get '/baby_sitters/:id', to: 'baby_sitter_registrations#show', as: :baby_sitter
  get '/listings', to: 'listings#index'
  resources :home

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
    before_action :authenticate_user!

    def index
        # User booking details
       @booking_details = BookingDetail.where(user_id: current_user.id) 
       @baby_sitter = BabySitterRegistration.where(user_id: current_user.id) 

       # Babysitter booking details
       @babysitter_booking = BookingDetail.where(baby_sitter_registration: current_user.baby_sitter_registration)
        
    end
    # update the status of booking
    def update
        @booking = BookingDetail.find(params[:id])
        @booking.update(status: "Accepted")

        redirect_to dashboard_index_path
    end
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/views/dashboard/index.html.erb
<% if user_signed_in?  && current_user.is_baby_sitter == true %>

<%#dashboard for the babysitter%>
 <% @baby_sitter.each do |babysitter|%>
  <div class="container">
  <h3> Welcome <%= babysitter.first_name.capitalize + ' ' + babysitter.last_name.capitalize %></h3> <br>
  <p class = "preview"><%= image_tag (babysitter.upload_image) if babysitter.upload_image.attached?%></p><div>
  <h4> Update Personal Details<%= link_to "Here", edit_user_registration_path %></h4><br>
  <div><h3><u>Account Details</u></h3></div><br>
  <p><strong>Country:</strong> <%= babysitter.country%></p>
  <p><strong>Prefered City:</strong> <%= babysitter.city %></p>
   <p><strong>Gender:</strong> <%= babysitter.gender %></p>
  <p><strong>Languages:</strong> <%= babysitter.language %></p>
  <p><strong>Available_Date:</strong> <%= babysitter.available_date %></p>
  <p><strong>About myself:</strong> <%= babysitter.description %></p>
  <p><strong>Amount/hr:</strong> <%= babysitter.amount %></p><br> 
  <div>
  <%= button_to "Edit Profile",edit_baby_sitter_registration_path(current_user.baby_sitter_registration),:method=>:get%><br>
  <%# <%= link_to "Delete", baby_sitter_registration_path(babysitter),data:{confirm:"Are you sure?"}, :method =>:delete %> 
  </div><br>
  <% end %>
  <%if @babysitter_booking .empty? %>
  <h3> There is No Bookings at this moment!</h3>
  <%else  %>
  <%#display the current booking details of a baby sitter %>
  <div><h3><u>My Current Bookings</u></h3></div>
  <table cellspacing="1" cellpadding="1">
  <thead>
    <tr>
      <th>CHILD NAME</th>&nbsp
      <th>AGE</th>&nbsp
      <th>CITY</th>
      <th>EMAIL_ID</th>
      <th>MOBILE</th>
      <th>DATE</th>
      <th>STATUS</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
  <% @babysitter_booking.each do |bookings| %>
  <tr>
  <td><%= bookings.name %></td>
  <td><%= bookings.age %></td>
  <td><%= bookings.city %></td>
  <td><%= bookings.user.email %></td>
  <td><%= bookings.number %></td>
  <td><%= bookings.date %></td>
  <td><%= bookings.status %></td>
  <td><%= link_to "Accept Booking", dashboard_path(bookings.id), method: :put %></td> 
  
  </tr>
  <% end %>
  </tbody>
  </table>
  <%end %>
<%#dashboard for the signed in users %>
<%else %>
  <div class ="container">
  <h4> Update Personal Details
  <%= link_to "Here", edit_user_registration_path %></h4><br>

  <%if @booking_details.empty? %>
 <%= "Sorry there is No Bookings at this moment!" %>
 
 <%else  %>
 <%#display booking details of a user %>
  <div><h2><u>My Booking Details</u></h2></div>
  <table cellspacing="1" cellpadding="1">
  <thead>
    <tr>
      <th><strong>CHILD NAME</strong></th>&nbsp
      <th><strong>AGE</strong></th>&nbsp
      <th><strong>CITY</strong></th>
      <th><strong>MOBILE</strong></th>
      <th><strong>DATE</strong></th>
      <th><strong>BABY SITTER</strong></th>
      <th><strong>STATUS</strong></th>

      <th colspan="3"></th>
    </tr>
  </thead>

 <tbody>
  <% @booking_details.each do |booking| %>
  <tr>
  <td><%= booking.name %></td>
  <td><%= booking.age %></td>
  <td><%= booking.city %></td>
  <td><%= booking.number %></td>
  <td><%= booking.date %></td>
  <td><%= booking.baby_sitter_registration.first_name %></td>
  <td><%= booking.status %></td>
  <td><%=link_to "Edit", [:edit, booking.baby_sitter_registration, booking]%></td>
  <td><%= link_to "Delete", [ booking.baby_sitter_registration, booking],data:{confirm:"Are you sure?"}, :method=>:delete%></td>  
</tr>
  <%end %>
</tbody>
</table>
 <%end%>
  
  <%end%>