config/routes.rb
Rails.application.routes.draw do
  root to: "home#index"
  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations'
  }
  
  resources :listings
  resources :baby_sitter_registrations do
  resources :booking_details 
  end
  resources :dashboard

  get '/baby_sitters/:id', to: 'baby_sitter_registrations#show', as: :baby_sitter
  get '/listings', to: 'listings#index'
  resources :home

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/booking_detail.rb
class BookingDetail < ApplicationRecord
  belongs_to :user
  belongs_to :baby_sitter_registration
  validates :age, numericality: true
  validates :number, numericality: true,length: { is: 10 }
end

app/controllers/booking_details_controller.rb
class BookingDetailsController < ApplicationController
before_action :authenticate_user!
before_action :find_booking,only: [:edit,:update,:destroy]
before_action :authorise_user!,only: [:edit,:update,:destroy]

def index
end
   #Display booking details of a user
   def show
    @booking = BookingDetail.find(params[:id])
  end
    # making new booking for a particular baby sitter
    def new
        @booking = BookingDetail.new
        @babysitter_id = params[:babysitter_id]
        @baby_sitter_registration = BabySitterRegistration.find(params[:baby_sitter_registration_id])
    end

    def create
        @baby_sitter_registration = BabySitterRegistration.find(params[:baby_sitter_registration_id])
        @booking = BookingDetail.new(booking_params)
        @booking.user_id=current_user.id
        @booking.baby_sitter_registration_id = params[:baby_sitter_registration_id]
        @booking.status = "Pending"
        if(@booking.save)
            redirect_to [@baby_sitter_registration, @booking],notice: "Booking Confirmed"
        else
            render 'new'
        end
    end
    
    # edit the booking details
    def edit
        @babysitter_id = @booking.baby_sitter_registration.id
        @baby_sitter_registration= @booking.baby_sitter_registration
      end

    def update
        if (@booking.update(booking_params))
            # redirect_to @booking
            redirect_to  dashboard_index_path, notice: "UPDATED!"
        else
            render 'edit'
        end
    end
    # delete a booking details
    def destroy
        @booking.delete
        redirect_to  dashboard_index_path
    end


    private

    def booking_params
        params.require(:booking_detail).permit(:name, :age, :number, :city, :date, :message, :baby_sitter_registration_id, :user_id)
    end

    def find_booking
        @booking = BookingDetail.find(params[:id])
    end

    def authorise_user!
        return true if current_user.id == @booking.user_id
    end
end

app/views/booking_details/_booking_form.html.erb
<%= form_with(model: [@baby_sitter_registration,booking_detail], local: true,class:"form") do |form| %>
  <% if booking_detail.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(booking_detail.errors.count, "error") %> prohibited this event from being saved:</h2>

      <ul>
        <% booking_detail.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

<div class= "container">
   <div><h2>  Booking For Baby Sitter</h2><div><br>

    <div class="field">
    <%= form.label :Name_of_child, :required => true,class:"col-5" %>
    <%= form.text_field :name,class:"col-6" %>
  </div>

  <div class="field">
    <%= form.label :Age_of_child, :required => true,class:"col-5" %>
    <%= form.text_field :age,class:"col-6" %>
  </div>

  <%# <div class="field">
    <%= form.label :Country, :required => true,class:"col-5" %>
    <%# <%= form.text_field :country,  :required => true, class:"col-6" %> 
  <%# </div> %> 

  <div class="field">
    <%= form.label :City , :required => true,class:"col-5" %>
    <%= form.text_field :city, :required => true,class:"col-6" %>
  </div>

  <div class="field">
    <%= form.label :Mobile_Number ,:required => true, class:"col-5" %>
    <%= form.text_field :number ,class:"col-6",  :required => true %>
  </div>

  <div class="field">
    <%= form.label :Booking_Date, class:"col-5" %>
    <%= form.date_select :date, :required => true, class:"col-6" %>
  </div>

  <div class="field">
    <%= form.label :Message, :required => true ,class:"col-5"%>
    <%= form.text_field :message, :required => true ,class:"col-6"%>
  </div>

  <%= form.hidden_field :baby_sitter_registration_id, value: "#{@babysitter_id}" %>
  <div class="field">
    <%= form.submit  %>
  </div>
  </div>
  <% end %>

app/views/booking_details/edit.html.erb
<%= render 'booking_form' ,booking_detail: @booking %>

app/views/booking_details/new.html.erb
<%= render 'booking_form' , booking_detail: @booking %>

app/views/booking_details/show.html.erb
<%# <p id="notice"><%= notice%> 
<div class="container"><br>
<h2 class="success"> Booking Details</h2><br>
<p><strong>Child Name: </strong><%= @booking.name %><br></p>
<p><strong>Age of Child: </strong><%= @booking.age %><br></p>
<p><strong>City: </strong><%= @booking.city %><br></p>
<p><strong>Mobile: </strong><%= @booking.number %><br></p>
<p><strong>Booking Date: </strong><%= @booking.date %><br></p>
<p><strong>Message: </strong><%= @booking.message %><br></p>
<%# <%= link_to "Edit Details", edit_booking_detail_path(@booking) %>
</div>