config/routes.rb
Rails.application.routes.draw do
  root to: "home#index"
  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations'
  }
  
  resources :listings
  resources :baby_sitter_registrations do
  resources :booking_details 
  end
  resources :dashboard

  get '/baby_sitters/:id', to: 'baby_sitter_registrations#show', as: :baby_sitter
  get '/listings', to: 'listings#index'
  resources :home

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/views/layouts/_nav-bar.html.erb
<% if user_signed_in? %>
<div class="nav-bar">

<ul>
 <li><%= link_to 'Home', home_index_path%></li> 
<li><%= link_to 'Profile' , dashboard_index_path %></li>
 <li><%= link_to 'Sign out' , destroy_user_session_path, method: :delete %> </li><%= image_tag("logo_icon.svg",width:'60px',height:'60px') %>
 
</ul>

<%else%>
<ul>
 <li><%= link_to 'Home', home_index_path %></li>
 <li><%= link_to 'Log In', new_user_session_path %><strong>/</strong></li>
<li><%= link_to 'Sign Up', new_user_registration_path %></li>

</ul>
<% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BabySitterApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  
  <section class= "nav-bar">
  <div class="logo"><%= link_to 'Find Babysitter', baby_sitter_registrations_path %></div>
  <nav >
    <%= render 'layouts/nav-bar' %>
    </nav>
  </section>
  
  <% flash.each do |key, value| %>
      <div class="alert alert-<%= key %>"><%= value %>
      <span class="closebtn" onclick="this.parentElement.style.display='none';">&times;</span> 
      </div>
    <% end %>
    <%= yield %> 
  </body>
 
</html>